// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'API KEY HERE',
    appId: '1:319928501602:web:9ff541d4f67dc8cbef583b',
    messagingSenderId: '319928501602',
    projectId: 'uf-parking-map',
    authDomain: 'uf-parking-map.firebaseapp.com',
    databaseURL: 'https://uf-parking-map-default-rtdb.firebaseio.com',
    storageBucket: 'uf-parking-map.appspot.com',
    measurementId: 'G-VKW78MTZP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'API KEY HERE',
    appId: '1:319928501602:android:d4122a79d7890c2def583b',
    messagingSenderId: '319928501602',
    projectId: 'uf-parking-map',
    databaseURL: 'https://uf-parking-map-default-rtdb.firebaseio.com',
    storageBucket: 'uf-parking-map.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'API KEY HERE',
    appId: '1:319928501602:ios:2f8b1d63af34d9a7ef583b',
    messagingSenderId: '319928501602',
    projectId: 'uf-parking-map',
    databaseURL: 'https://uf-parking-map-default-rtdb.firebaseio.com',
    storageBucket: 'uf-parking-map.appspot.com',
    iosClientId:
        '319928501602-09umuahlj5brji033qtrgvlal87tjpno.apps.googleusercontent.com',
    iosBundleId: 'com.example.ufParkingMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'API KEY HERE',
    appId: '1:319928501602:ios:2f8b1d63af34d9a7ef583b',
    messagingSenderId: '319928501602',
    projectId: 'uf-parking-map',
    databaseURL: 'https://uf-parking-map-default-rtdb.firebaseio.com',
    storageBucket: 'uf-parking-map.appspot.com',
    iosClientId:
        '319928501602-09umuahlj5brji033qtrgvlal87tjpno.apps.googleusercontent.com',
    iosBundleId: 'com.example.ufParkingMap',
  );
}
